server:
  port: ${env.SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${env.MYSQL_HOST}:${env.MYSQL_PORT}/${env.MYSQL_DATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=${env.MYSQL_USE_SSL}&allowPublicKeyRetrieval=true
    username: ${env.MYSQL_USER}
    password: ${env.MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      springframework:
        level: DEBUG