CREATE TABLE IF NOT EXISTS `client` (
	`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	`first_name` VARCHAR(20) NOT NULL,
	`last_name` VARCHAR(20) NOT NULL,
	`email` VARCHAR(50) UNIQUE NOT NULL,
	`cpf` VARCHAR(12) UNIQUE NOT NULL,
	`date_of_birth` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;