CREATE TABLE IF NOT EXISTS `client` (
	`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	`first_name` VARCHAR(20) NOT NULL,
	`last_name` VARCHAR(20) NOT NULL,
	`cpf` VARCHAR(12) NOT NULL,
	`date_of_birth` DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;